import { login } from "./auth";
import {
  getBio,
  updateBio,
  addSocial,
  deleteSocial,
  updateSocial,
  addExperience,
  deleteExperience,
  updateExperience,
  addSkills,
  deleteSkills,
  updateSkills,
  addPortofolio,
  deletePortofolio,
  updatePortofolio,
  addEducation,
  deleteEducation,
  updateEducation,
} from "./bio";

export {
  login,
  getBio,
  updateBio,
  addSocial,
  deleteSocial,
  updateSocial,
  addExperience,
  deleteExperience,
  updateExperience,
  addSkills,
  deleteSkills,
  updateSkills,
  addPortofolio,
  deletePortofolio,
  updatePortofolio,
  addEducation,
  deleteEducation,
  updateEducation,
};
